name: V2EX Daily Mission

on:
  schedule:
    - cron: '30 */4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run checkin script
      env:
        V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
      run: python3 v2ex-checkin.py

    - name: Run patrol script
      env:
        V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
      run: python3 v2ex-patrol.py